spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_reminder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
yaml server:
  address: 0.0.0.0
  port: 8080

server:
  port: 8443            # любой свободный
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: ai-reminder
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

n8n:
  webhook:
    url: https://n8n.gigafs.v6.navy/webhook-test/webhook/ai-reminder

websocket:
  endpoint: /ws          #  <–– любой путь, например /ws
  prefix:
    app:   /app
    topic: /topic