CREATE TABLE outbox_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   reminder_id BIGINT,
   user_id BIGINT,
   payload VARCHAR(255),
   processed BOOLEAN NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_outbox_notifications PRIMARY KEY (id)
);

CREATE TABLE reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   title VARCHAR(255),
   description VARCHAR(2000),
   scheduled_at TIMESTAMP WITHOUT TIME ZONE,
   location VARCHAR(255),
   state VARCHAR(255),
   source VARCHAR(255),
   external_calendar_event_id VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_reminders PRIMARY KEY (id)
);