-- V1__init.sql  (без истории Flyway)

-------------------------------------------------------------------------------
-- 1. Секвенс для пользователей
-------------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS user_id_seq
  AS BIGINT
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1;

-------------------------------------------------------------------------------
-- 2. Пользователи
-------------------------------------------------------------------------------
CREATE TABLE users (
  id        BIGINT NOT NULL DEFAULT nextval('user_id_seq'),
  username  VARCHAR(255) NOT NULL,
  password  VARCHAR(255) NOT NULL,
  role      VARCHAR(255) NOT NULL,
  tg_id     VARCHAR(255),
  CONSTRAINT users_pkey        PRIMARY KEY (id),
  CONSTRAINT uk_users_username UNIQUE (username),
  CONSTRAINT uk_users_tg_id    UNIQUE (tg_id)
);

-------------------------------------------------------------------------------
-- 3. Outbox для уведомлений
-------------------------------------------------------------------------------
CREATE TABLE outbox_notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reminder_id BIGINT,
  user_id     BIGINT,
  payload     TEXT,
  processed   BOOLEAN NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE
);

-------------------------------------------------------------------------------
-- 4. Напоминания
-------------------------------------------------------------------------------
CREATE TABLE reminders (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   BIGINT,
  title     VARCHAR(255),
  description VARCHAR(2000),
  scheduled_at TIMESTAMP WITH TIME ZONE,
  location  VARCHAR(255),
  state     VARCHAR(255),
  source    VARCHAR(255),
  external_calendar_event_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE
);

-------------------------------------------------------------------------------
-- 5. Telegram-чаты
-------------------------------------------------------------------------------
CREATE TABLE telegram_chats (
  tg_id   VARCHAR(255) PRIMARY KEY,
  chat_id BIGINT NOT NULL
);